config/routes.rb
Rails.application.routes.draw do
  root 'livros#index'
  resources :livros
  resources :pessoas

end

app/models/livro.rb
class Livro < ActiveRecord::Base
  belongs_to :pessoa, class_name: 'Pessoa'
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  has_many :livros, class_name: 'Livro', primary_key: 'id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro was successfully created.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:autor, :titulo, :editora, :edicao, :dono, :emprestado, :pessoa_id)
    end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :email, :telefone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treecko</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/livros/_form.html.erb
<%= form_for(@livro) do |f| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% @livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :editora %><br>
    <%= f.text_field :editora %>
  </div>
  <div class="field">
    <%= f.label :edicao %><br>
    <%= f.number_field :edicao %>
  </div>
  <div class="field">
    <%= f.label :dono %><br>
    <%= f.text_field :dono %>
  </div>
  <div class="field">
    <%= f.label :emprestado %><br>
    <%= f.check_box :emprestado %>
  </div>
  <div class="field">
    <%= f.label :pessoa %><br>
    <%= f.select('pessoa_id', Pessoa.all.collect {|p| [p.nome, p.id]}, {include_blank:true}) %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/livros/edit.html.erb
<h1>Editing livro</h1>

<%= render 'form' %>

<%= link_to 'Show', @livro %> |
<%= link_to 'Back', livros_path %>

app/views/livros/index.html.erb
<h1>Livros</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Autor</th>
      <th>Titulo</th>
      <th>Editora</th>
      <th>Edicao</th>
      <th>Dono</th>
      <th>Está emprestado?</th>
      <th>Para quem?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= livro.autor %></td>
        <td><%= livro.titulo %></td>
        <td><%= livro.editora %></td>
        <td><%= livro.edicao %></td>
        <td><%= livro.dono %></td>
        
         <% if livro.emprestado ==false %> 
            <td> <span class= "glyphicon glyphicon-remove"> </span></td> 
        <td> <span> -- </span></td>
        <% else %>
           <td> <span class= "glyphicon glyphicon-ok"> </span></td> 
        <td><%= livro.pessoa.nome %></td>
        <% end %>
        <td><%= link_to 'Exibir', livro %></td>
        <td><%= link_to 'Editar', edit_livro_path(livro) %></td>
        <td><%= link_to 'Apagar', livro, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="pull-right">
<%= link_to 'Novo Livro', new_livro_path, :class => "btn btn-primary" %>
<%= link_to 'Novo Amigo', new_pessoa_path, :class => "btn btn-primary" %>
</div>

app/views/livros/new.html.erb
<h1>Novo livro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', livros_path, :class => "btn btn-primary" %>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @livro.titulo %>
</p>

<p>
  <strong>Editora:</strong>
  <%= @livro.editora %>
</p>

<p>
  <strong>Edicao:</strong>
  <%= @livro.edicao %>
</p>

<p>
  <strong>Dono:</strong>
  <%= @livro.dono %>
</p>

<p>
  <strong>Está emprestado?</strong>
  <%= @livro.emprestado %>
</p>

<% if @livro.emprestado %>

<p>
  <strong>Para quem?</strong>
  <%= @livro.pessoa.nome %>
</p>

<% end %>

<%= link_to 'Editar', edit_livro_path(@livro) %> |
<%= link_to 'Voltar', livros_path %>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Amigos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.email %></td>
        <td><%= pessoa.telefone %></td>
        <td><%= link_to 'Exibir', pessoa %></td>
        <td><%= link_to 'Editar', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Apagar', pessoa, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="pull-right">
<%= link_to 'Novo Amigo', new_pessoa_path, :class => "btn btn-primary" %>
<%= link_to 'Catálogo', livros_path, :class => "btn btn-primary" %>

</div>

app/views/pessoas/new.html.erb
<h1>Novo Amigo</h1>

<%= render 'form' %>

<%= link_to 'Voltar', pessoas_path, :class => "btn btn-primary" %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>email:</strong>
  <%= @pessoa.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @pessoa.telefone %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>